name: 'docker build'
author: 'triptixx'
description: 'A Action CI plugin for tagging and pushing built Docker images'
inputs:
  docker_username:
    description: 'docker registry username'
    required: true
  docker_password:
    description: 'docker registry password'
    required: true
  from:
    description: 're-tag from this repo'
  repo:
    description: 'tag to this repo/repo to push to'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'package'
  color: 'blue'
